プライバシーポリシーを追加
takizawa-hackathon/takizawa-hackathon.github.io pull request #77
Opened 2024-01-05 14:51 UTC by rkonno

### 変更点

- プライバシーポリシーに関するページを追加
- 各ページのフッターにプライバシーポリシーのページへのリンクを追加

### 2024/01/05時点スクショ

![screencapture-127-0-0-1-5500-privacy-2024-01-05-23_51_21](https://github.com/takizawa-hackathon/takizawa-hackathon.github.io/assets/12765236/144600c9-2f45-46a8-a526-a93c1d41f894)

2024-01-05 15:27 UTC, mattyan06 requested changes
コメントしました！

2024-01-05 15:27 UTC, mattyan06 commented on index.html
> +            &copy; 2023 滝沢ハッカソン運営委員会 | Design by <a href="https://uicookies.com">uiCookies</a> and modify by <a
ついでに2024に更新してもらえると！

2024-01-05 15:27 UTC, mattyan06 commented on privacy/index.html
> +                <p>滝沢ハッカソン運営委員会は、利用者よりお預かりした個人情報を適切に管理し、次のいずれかに該当する場合を除き、個人情報を第三者に開示しません。</p>
企業賞贈呈時も共有する可能性がある旨追加したいです

2024-01-06 02:52 UTC, rkonno commented on index.html
> +            &copy; 2023 滝沢ハッカソン運営委員会 | Design by <a href="https://uicookies.com">uiCookies</a> and modify by <a
JavaScriptで自動更新するように変更しました！

2024-01-06 02:54 UTC, rkonno commented on privacy/index.html
> +                <p>滝沢ハッカソン運営委員会は、利用者よりお預かりした個人情報を適切に管理し、次のいずれかに該当する場合を除き、個人情報を第三者に開示しません。</p>
確かにその記載もあったほうが良いですね！以下の一文を追加しました。

`利用者に企業賞の副賞を贈呈するために、スポンサー企業に対して利用者の連絡先情報（お名前、メールアドレス、電話番号等）を提供する場合`

2024-01-06 02:59 UTC, mattyan06 approved these changes
LGTM!

2024-01-06 03:13 UTC, merged